FROM maven 

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip 

WORKDIR "/app"

COPY . /app

RUN mkdir -p /mvn/.m2nrepo/repository
RUN mvn -Dmaven.repo.local=/mvn/.m2nrepo/repository dependency:go-offline
RUN mvn -Dmaven.repo.local=/mvn/.m2nrepo/repository install
